language: c
sudo: true
git:
  submodules: false
compiler:
- gcc
python:
- '2.6'
addons:
  postgresql: '9.2'
  artifacts: true
services:
- postgresql
install:
- pip install --user setuptools
- mkdir -p ${TRAVIS_BUILD_DIR}/tools
- cd ${TRAVIS_BUILD_DIR}/tools
- sudo apt-get -y update
- sudo apt-get install postgresql-9.2 postgresql-client-9.2
- sudo apt-get install postgresql-server-dev-9.2
- wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.linux.bin.tar.gz
- tar -zxvf doxygen-1.8.4.linux.bin.tar.gz -C ${TRAVIS_BUILD_DIR}/tools
- sudo apt-get install -y rpm
before_script:
- export PATH=${TRAVIS_BUILD_DIR}/tools/bin:${TRAVIS_BUILD_DIR}/tools/doxygen-1.8.4/bin:$PATH
script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
- cmake ..
- make
- make package
- make gppkg
notifications:
  email:
    recipients:
    - xtang@pivotal.io
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: ROFHb6HPEC+WWTM7fOtzczw894ANoqEEZnYK8J9YFLF0G6cDqW407eiqyRs4goB9y6oQcqsEpisF6Ioa+pCjhqpflNeibiKPG4wGGFKeFPxHJYbTKL/3xu1yTVXjc26x/dgZYxikNrrMzHQGEQmNeZuxT6vqp6RqAKmYwkFnmECAkJM2PLX4mXe39JmMkD2+cs6UfZLS7B2tCc8Jf3FGt2FLCUt4qX5cFHwUp70Wf40bXqvrbSgvorm2yBZe7xchZF6AaFNNTFkFpY0sBssYZdKr65e1msLAS1J4MNadhoC2XAieXEgSfBLNcgMIgm8lncCXGR69sBeXj6Wz3VOvsBc/EU49AkWtZTBIniFmfjmbfFMRVEEbM6dG0evzoW1CjP0CLGhHOItTZMl16w7AX2qBoQ57aQWkHnUlMk0IZjG3Tv8/BILHs2ty2GJvOrUpjjloEMluzcl9LPQJ5ZW+p7M2s9M0nBcHzvcuL1HV7Srha5zDz9CNpqVLfLTMrY6pCAu8wyQbldM46xqc5tMWjvP02OGNo5APjAjNgZBXkMNDnJ6/Mqx0LWDpT3TZIp6SkMIFsEwUufclOZz5W1Dwfnh7q17nJlgifWEi+XtYH8zpeA89YA05chyLT1KklimVlRsEbVYWklOv4ddUGfttN1OYKFRPj8SCcXJjKUJg3N8=
  file:
    - madlib-1.8dev-Linux.rpm
  on:
    repo: mktal/incubator-madlib
    branch: travis-ci
    # tags: true # deployed when a tag is applied
  skip_cleanup: true
